### ISSUE TITLE
Why did you remove Google Gemini?

### ISSUE THREAD

**Issue by alr86** [m7medVision/lazycommit#4]
I haven't OpenAI API Key, Why did you remove Gemini?

**Comment by m7medVision** [comment]
I gonna return it soon...

**Comment by m7medVision** [comment]
Done

**Comment by alr86** [comment]
Thanks. However, `m7medvision/lazycommit@latest` is not working correctly, but `m7medvision/lazycommit` works fine.

**Comment by m7medVision** [comment]
I'm not sure why this is happening. It might be because the 'latest' tag
isn't pointing to the most recent version. I'm relatively new to developing
npm packages, so I'm still learning the intricacies.
